In [4]:
import torch

# set device to GPU if available, otherwise use CPU
device = (
    torch.accelerator.current_accelerator().type
    if torch.accelerator.is_available()
    else "cpu"
)
print(f"Using {device} device")

Using mps device


In [5]:
# create tensor with 100 rows and 10 columns, filled with random values
X = torch.randn(10000000000, 1)
X.to(device)  # move tensor to GPU if available

tensor([[ 2.5992],
        [-0.6098],
        [ 0.4673],
        ...,
        [-0.7396],
        [-0.3489],
        [-0.4044]], device='mps:0')

In [ ]:
import torch
from torch import nn

dim_size = 3
arpit_embedding = nn.Embedding(1, dim_size)
# set weights of the embedding layer to value [0.5, 0.1, 0.2]
arpit_embedding.weight.data = torch.tensor([[0.5, 0.1, 0.2]])
print(arpit_embedding.weight)


msds_students = nn.Embedding(79, dim_size)
# print(msds_students.weight)


ignacio_id = 10
yancy_id = 20

ts = torch.LongTensor([[ignacio_id, yancy_id, ignacio_id]])
some_embeddings = msds_students(ts)
print(some_embeddings)
print(some_embeddings.shape)

Parameter containing:
tensor([[0.5000, 0.1000, 0.2000]], requires_grad=True)
tensor([[[ 0.1171,  1.3040,  1.5243],
         [ 1.5450,  1.1528, -0.2240],
         [ 0.1171,  1.3040,  1.5243]]], grad_fn=<EmbeddingBackward0>)
torch.Size([1, 3, 3])


In [34]:
a = torch.tensor([[1, 2, 3], [3, 4, 5]])
print(a.shape)
b = a.reshape(3, -1)
print(b.shape)
c = b.sum()
print(c)

torch.Size([2, 3])
torch.Size([3, 2])
tensor(18)
